service: sns-to-apigw-demo

plugins:
  - serverless-apigateway-service-proxy
  - serverless-cloudformation-sub-variables

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:ListEventSourceMappings
      Resource: '*'
    - Effect: Allow
      Action: lambda:UpdateEventSourceMapping
      Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:event-source-mapping:*

custom:
  apiGatewayServiceProxies:
    - kinesis:
        path: /kinesis
        method: post
        streamName: { Ref: 'MyStream' }
        request:
          template:
            text/plain: 
              Fn::Sub:
                - | 
                  #set($msgBody = $util.parseJson($input.body))
                  #set($msgId = $msgBody.MessageId)
                  {
                      "Data": "$util.base64Encode($input.body)",
                      "PartitionKey": "$msgId",
                      "StreamName": "#{MyStreamArn}"
                  }
                - MyStreamArn:
                    Fn::GetAtt: [MyStream, Arn]

functions:
  api-gw:
    handler: functions/apigw.handler
    events:
      - http:
          path: /
          method: post
  
  kinesis:
    handler: functions/kinesis.handler
    environment:
      KINESIS_ARN:
        Fn::GetAtt: [MyStream, Arn]
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt: [MyStream, Arn]

# you can add CloudFormation resource templates here
resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic

    MyStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: my-stream
        ShardCount: 1
